#このSpring Bootアプリの名前は myapp です
spring.application.name=myapp
#localhostの3306番ポートにあるMariaDBの myapp データベースにつないで//
spring.datasource.url=jdbc:mariadb://localhost:3306/myapp
#MariaDBに rootユーザーでログインする。//
spring.datasource.username=root
#パスワードが空欄という設定。//
spring.datasource.password=